### ISSUE TITLE
[watchdog_node] Allow non-continuous subscriptions

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_apps#53]
For checking the camera node, I don't want to remain subscribed permanently, so I think we need to add an option for topic-based nodes to only recheck after a fixed interval. This is very easy to add with the current code.

**Comment by cburbridge** [comment]
You could subscribe/monitor the `/camera_info` subtopic instead for lower bandwidth, although I suppose the pointcloud stream could stop even while camera_info continues.
